CREATE DATABASE IF NOT EXISTS prueba_tecnica_intricom;
USE prueba_tecnica_intricom;

CREATE TABLE IF NOT EXISTS Hotel (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  Address VARCHAR(255),
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CLIENT (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  Address VARCHAR(255),
  Phone VARCHAR(50),
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS HotelBooking (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  HotelId INT NOT NULL,
  NAME VARCHAR(255),
  Address VARCHAR(255),
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  ClientId INT NOT NULL,
  CONSTRAINT FK_HotelBooking_Hotel FOREIGN KEY (HotelId) REFERENCES Hotel(Id),
  CONSTRAINT FK_HotelBooking_Client FOREIGN KEY (ClientId) REFERENCES CLIENT(Id)
);